### ISSUE TITLE
AJAX calls connecting to DB

### ISSUE THREAD

**Issue by cmahaffey** [nilocy/ACK_attack#1]
We have a search function that goes through our database to find data about a movie and said movie's soundtrack.  We want to make AJAX calls to two APIs based off this data. We are running into issues where the page needs to be redirected in order for the AJAX calls to fire, where as we would like to have everything fire on the user profile page.

The post request currently creates a ruby variable, which is then passed to JS. I think we have to make an AJAX call to our own database before we can pass it through our AJAX calls, but I want to make sure before I go down that route.

**Comment by amadden80** [comment]
That makes perfect sense to me as said in person.

```
$.ajax({
  url: '/thingIWant',
  method: 'get',
  success: function(data){
    $.ajax({
     url: '/thatotherthing'
    })
  }
})
```

**Comment by emilylordahl** [comment]
Can you close this issue? :-)
